version: '3.4'
services:
  distributeddpapidemo:  
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$CREDENTIAL_PLACEHOLDER$
      - ConnectionStrings__DefaultContext=user id=postgres;password=$CREDENTIAL_PLACEHOLDER$;host=host.docker.internal;port=5432;database=postgres