# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  distributeddpapidemo:
    image: distributeddpapidemo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6001:6001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
