# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
version: '3.4'
services:
  distributeddpapidemo:
    image: distributeddpapidemo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6001     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:6001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro  
      - ~/keys:/app/keys:rw
    deploy:
      mode: replicated
      replicas: 3     
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro      
    depends_on:
      - distributeddpapidemo
    ports:
      - "4000:4000"
networks:
  default:
    driver: bridge
    name: test     
