version: '3.4'
services:
  distributeddpapidemo:  
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Versuv10us
      - ConnectionStrings__DefaultContext=user id=postgres;password=postgres;host=host.docker.internal;port=5432;database=postgres
  postgres-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres